### ISSUE TITLE
K8SSAND-870 ⁃ IPCControllerTest fails when run on MacOS

### ISSUE THREAD

**Issue by emerkle826** [k8ssandra/management-api-for-apache-cassandra#128]
When trying to run IPCControllerTest on MacOS, the test fails with:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.447 s <<< FAILURE! - in com.datastax.mgmtapi.ipc.IPCControllerTest
[ERROR] clientServerTest(com.datastax.mgmtapi.ipc.IPCControllerTest)  Time elapsed: 0.414 s  <<< ERROR!
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.epoll.EpollServerDomainSocketChannel
    at com.datastax.mgmtapi.ipc.IPCControllerTest.clientServerTest(IPCControllerTest.java:123)
Caused by: java.lang.reflect.InvocationTargetException
    at com.datastax.mgmtapi.ipc.IPCControllerTest.clientServerTest(IPCControllerTest.java:123)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.Native
    at com.datastax.mgmtapi.ipc.IPCControllerTest.clientServerTest(IPCControllerTest.java:123)
```

Epoll is not available on MacOS, so it should try to use NIO in this case.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-870) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-870
┆Priority: Medium

**Comment by emerkle826** [comment]
Little debugging on an old mac, I think I found the issue. When the IPCControllerTest starts up, it creates a netty server, which ends up initializing here:
https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/master/management-api-common/src/main/java/com/datastax/mgmtapi/ipc/IPCController.java#L75-L82
```java
        if (isClient)
        {
            b = b.channel(EpollDomainSocketChannel.class);
        }
        else
        {
            b = b.channel(EpollServerDomainSocketChannel.class);
        }
```
So the server bit in the test is forcing Epoll, which doesn't exist on MacOS

**Comment by jsanda** [comment]
@emerkle826 nice find! Can you submit a PR to fix it?
