### ISSUE TITLE
Full query logging API endpoint

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/management-api-for-apache-cassandra#131]
Cassandra 4.0.0 added a full query logging facility, and configurations supporting this feature have now been added to the config builder [here](https://github.com/datastax/cass-config-definitions/pull/65).

An additional step is required to turn on full query logging; the user needs to run `nodetool enablefullquerylog`. jdonenine has mentioned that the historical practice in such cases has been to add a management API endpoint to enable the functionality.

This ticket to hold discussion on this topic and confirm that this is how we'd like to do things + track implementation once confirmed.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-905) by [Unito](https://www.unito.io)
┆Reviewer: 5b3c004b70b3b52e40050e56
┆Issue Number: K8SSAND-905
┆Priority: Medium

**Comment by emerkle826** [comment]
Once https://github.com/datastax/cass-config-definitions/pull/65 is merged, config builder will have all the configuration options needed for configuring FQL (Full Query Logging). When deploying K8ssandra, all the desired FQL configuration would happen before Cassandra is started, so to enable FQL, all that needs to be exposed through Management API is a way to enable (and possibly disable and reset) the logging.

Considering this, the question comes about implementing the endpoint in Management API: Do we provide a way to override any of the FQL options?

**Pros/Cons:**
If FQL options aren't expected to be changed/altered from how they are initially configured, then the REST endpoint doesn't really need to take any of the options and can be a simple `enable` endpoint that relies on all the config in `cassandra.yaml`. This would make the implementation very simple and straight forward.

If the options are expected to be changed, implementing them now will make it slightly more complex, but it would eliminate the need to revisit the implementation to add the capabilities later.

**Comment by Miles-Garnsey** [comment]
Draft PR #135 opened for comment.
