### ISSUE TITLE
K8SSAND-1572 ⁃ Investigate trimming images by basing them off minimal images

### ISSUE THREAD

**Issue by emerkle826** [k8ssandra/management-api-for-apache-cassandra#197]
### Issue
In light of adding the CDC agent to the Management API images, causing the images to grow about 40 MB, we would like to look into shrinking the images size by basing them off of a smaller [RH UBI](https://hub.docker.com/r/redhat/ubi8-minimal) or [SLE BCI](https://registry.suse.com/static/bci/bci-minimal/index.html) image.

### Goal
The goal of this issue is to see how much effort it will take to build an image based off a smaller base image, and how much saving can be had doing so.

### Additional Considerations
It might be desired to not even include the CDC agent in the Management API images, and have something like [K8ssandra Operator](https://github.com/k8ssandra/k8ssandra-operator) add the CDC agent via a K8s volume mount when desired.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1572) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1572
┆priority: Medium

**Comment by jsanda** [comment]
@emerkle826 can you please provide a planning poker estimate.

**Comment by emerkle826** [comment]
I think this one is done for now
