### ISSUE TITLE
Expose the Cassandra metrics registry through a Prometheus endpoint

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/management-api-for-apache-cassandra#228]
In order to reduce the number of loaded agents and simplify the stack, we'd need to expose the Cassandra/DSE metrics registry in the mgmt api agent, using the following prototype as a base: https://github.com/burmanm/mcac-revisit

The new endpoint should be disabled by default and enabled through an env variable: `MGMT_API_METRICS_ENDPOINT=enabled`

The port on which metrics are exposed should also be configurable through an env variable, and default to port 9104 if the env variable doesn't exist: `MGMT_API_METRICS_PORT=9104`

No metric filtering should be done in this first implementation.

**Comment by jsanda** [comment]
Does having an additional Java agent cause overhead?

How does having a metrics collector within management-api simply the stack? Anything beyond not having to manage a separate git repo?

Is there a possibility someone would want to use the collector on its own, independent of management-api?

**Comment by adejanovski** [comment]
> Does having an additional Java agent cause overhead?

There's a size overhead for the docker images.

> How does having a metrics collector within management-api simply the stack? Anything beyond not having to manage a separate git repo?

It's one less dependency to manage, which is a simplification of the stack for us. The lifecycle of the mgmt-api and the metrics collector would be the same, making upgrades simpler.

> Is there a possibility someone would want to use the collector on its own, independent of management-api?

I think that's out of scope for us. MCAC will live on for folks not using the management api.

**Comment by burmanm** [comment]
> I think that's out of scope for us. MCAC will live on for folks not using the management api.

Why would they? MCAC is bad even for them.

**Comment by jsanda** [comment]
I think Alex was referring to people who are using MCAC outside of Kubernetes. Whether or not they choose to use MCAC isn't our concern. Furthermore, we are not going to make any extra effort (if were it needed) to make the MCAC replace work outside of Kubernetes, and more specifically outside of cass-operator/k8ssandra-operator.
