### ISSUE TITLE
Make mgmt-api work with modern Java versions

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/management-api-for-apache-cassandra#239]
The management-api currently requires JDK8 to run correctly the tests or deploy. We really need to move on to a newer version, at least 11 (preferably including 17, as that's the next version Cassandra will support).

**Comment by adejanovski** [comment]
Don't we already build images with both jdk8 and jdk11? 🤔

**Comment by burmanm** [comment]
At least the Dockerfile 4.1 says:

FROM --platform=$BUILDPLATFORM maven:3.6.3-jdk-8-slim as builder

So the build of mgmt-api itself is done with JDK8

**Comment by emerkle826** [comment]
> FROM --platform=$BUILDPLATFORM maven:3.6.3-jdk-8-slim as builder

That line is there to build the Management API jar files as the project still requires JDK8. The C* 3.11, 4.0 and 4.1 images built are based on the base Cassandra images from DockerHub. Cassandra 4.1 uses JDK11 (see [here](https://hub.docker.com/layers/library/cassandra/4.1.0/images/sha256-1bb39a865dea247fbfbc391630952082dea633f81e3790c7f6b70c237d878b70?context=explore)), Cassandra 4.0 uses JDK11 as well (see [here](https://hub.docker.com/layers/library/cassandra/4.0.7/images/sha256-1ad029264fb995930fdce2991463ab8837b54d0251f3edb8848397496af94186?context=explore)). Cassandra 3.11 uses JDK8 still (see [here](https://hub.docker.com/layers/library/cassandra/3.11.14/images/sha256-03059dcd6a2d218e675dee71e8607fb62c5048ff8b4b9159b6de29f1cd3fb8b5?context=explore))
