### ISSUE TITLE
new metrics collector provide the snapshot information?

### ISSUE THREAD

**Issue by shaotingcheng** [k8ssandra/management-api-for-apache-cassandra#291]
I'm looking for the Cassandra exporter who will expose the information for snapshots.

Does the new metrics collector provide the snapshot information? (not the case in MCAC)
Or where can I get the full metric samples?

I will appreciate if any feedback.

Regards
ShaoTing

**Comment by burmanm** [comment]
Which snapshots are you referring to? SSTable snapshots or Histogram snapshots? The metric collector provides everything that's registered to CassandraMetrics, nothing else.

**Comment by shaotingcheng** [comment]
@burmanm  I mean the information from `nodetool listsnapshots`.
Could you please tell me where to check "CassandraMetrics". 
I am looking for a full list of metrics that the new metric collector provides.

**Comment by burmanm** [comment]
listsnapshots is not a metric.

Here you go for metrics documentation: https://cassandra.apache.org/doc/latest/cassandra/operating/metrics.html

**Comment by shaotingcheng** [comment]
Thanks, noted. Just closed this ticket.
