### ISSUE TITLE
Expose running tasks as metrics

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/management-api-for-apache-cassandra#293]
Cassandra exposes the progress of running tasks (compaction, upgradesstable, cleanup, streaming, etc...) through MBeans but  not as metrics.
For more convenient access we should make these available as metrics in the metric endpoint, so that they can be scraped.
This means coming up with a series format that allows tracking the progress of each type of task and remove the metrics once the operation is finished.

```[tasklist]
### Definition of Done
- [ ] Active compactions (id, progress, keyspace, tablename) are exposed as metrics
- [ ] Active streaming sessions (id, host, peer, direction, percentProgress) are exposed as metrics
- [ ] Sstable operations: cleanup, upgradesstable, scrub (id, keyspace, tablename, progress) are exposed as metrics
```

**Comment by burmanm** [comment]
One more thing to add, we should also add metric for our own internal Jobs that are running (how many are running, how many are queued etc)

**Comment by adejanovski** [comment]
which internal jobs are you referring to?

**Comment by burmanm** [comment]
mgmt-api's job queues (async calls)

**Comment by adejanovski** [comment]
I've updated the definition of done @burmanm. See if it matches and if you think of missing operations/jobs there.
