### ISSUE TITLE
Integration tests for v1 endpoints

### ISSUE THREAD

**Issue by emerkle826** [k8ssandra/management-api-for-apache-cassandra#362]
We don't have many, but the Integration tests don't cover any of the `v1` endpoints. We should write some where appropriate:

https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/master/management-api-server/src/test/java/com/datastax/mgmtapi/BaseDockerIntegrationTest.java#L33-L35

Tests should cover the endpoints in the resources in the [v1](https://github.com/k8ssandra/management-api-for-apache-cassandra/tree/master/management-api-server/src/main/java/com/datastax/mgmtapi/resources/v1) package.

**Comment by burmanm** [comment]
We do?

NonDestructiveOpsIT.java:    URIBuilder uriBuilder = new URIBuilder("http://localhost:8080/api/v1/ops/node/schema/versions");
NonDestructiveOpsIT.java:    URIBuilder uriBuilder = new URIBuilder("http://localhost:8080/api/v1/ops/node/repair");

Rest are cases where we can't really test them, such as async decommission.

**Comment by emerkle826** [comment]
I stand corrected. Closing this then.
