### ISSUE TITLE
Fix RingRange string method

### ISSUE THREAD

**Issue by emerkle826** [k8ssandra/management-api-for-apache-cassandra#383]
On this line:
https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/feature/client-gen/management-api-server/src/main/java/com/datastax/mgmtapi/resources/v2/RepairResourcesV2.java#L132
The logic incorrectly chops 2 characters off the end of the string. It should only chop 1.

**Comment by Miles-Garnsey** [comment]
Merged on the integration branch, closing.
