### ISSUE TITLE
K8SSAND-159 ⁃ Timeout on decommissioning node

### ISSUE THREAD

**Issue by sandoichi** [k8ssandra/management-api-for-apache-cassandra#41]
Currently there is a 30 second timeout in the mgmt api for the `ops/node/decommission` endpoint it will time out because the server sleeps for 30 seconds and then can take a while to finish decommissioning depending on how much data is in there.

Ideally we could change the decomm endpoint to a fire & forget mode instead.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-159) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-159
┆Priority: Medium

**Comment by burmanm** [comment]
Hey, this ticket was actually implemented some time ago (but forgotten to mention here):

https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/22ba959095ba4e5912c29df22a6c6ff3c70af86b/management-api-server/src/main/java/com/datastax/mgmtapi/resources/v1/NodeOpsResources.java#L37

So calling ``/api/v1/ops/node/decommission`` causes the decommission to happen in async matter. It will return a jobId which you can poll, but there's no need, so fire and forget works fine.
