### ISSUE TITLE
Missing image of cass-management-api 4.1.3

### ISSUE THREAD

**Issue by victorgitmain** [k8ssandra/management-api-for-apache-cassandra#424]
As I understand the request to add this image was already merged
https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/397

but they are missing in the docker repo 
https://hub.docker.com/r/k8ssandra/cass-management-api/tags?page=1&name=4.1.3
Is this some bug or maybe there is still a pending Update?

**Comment by emerkle826** [comment]
@victorgitmain The new versions have been added via #420 recently, however, the images will not be pushed to Docker Hub until we cut a release. We are planning that shortly, but there is an outstanding issue (#422) that we need to get reviewed and merged first. Once #423 is merged, we can publish all the new images.

**Comment by victorgitmain** [comment]
Thank you for the fast reply ,will follow the mentioned issue

**Comment by emerkle826** [comment]
@victorgitmain We've just released v0.1.71 of Management API. Images with the latest Cassandra versions (4.0.11 and 4.1.3) should now be available in Docker Hub.
