### ISSUE TITLE
Add `tar` to the DSE images

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/management-api-for-apache-cassandra#465]
When troubleshooting misbehaving pods it's often required to be able to extract a large number of files from the container outside of it.
`tar` is very handy to perform such operations and is present in the Cassandra images but not the DSE ones.
We'd need to add `tar` to the DSE images as well. It is also mandatory to be able to use `kubectl cp` commands.

```[tasklist]
### Definition of Done
- [ ] `tar` is added to the dse images
```

**Comment by marcio-pessoa** [comment]
I never found a solution to this problem, so I finally wrote an application to copy files without tar.
It is just a beta, but is working fine on my environment.

https://github.com/marcio-pessoa/kubectl-cp
