### ISSUE TITLE
CDC is not working in the OSS images (at least not UBI)

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/management-api-for-apache-cassandra#510]
When starting the CDC enabled bundles, we end up with:

```
[cassandra@test-cluster-dc1-default-sts-0 cassandra]$ cat stdout.log 
Error occurred during initialization of VM
agent library failed to init: instrument
[cassandra@test-cluster-dc1-default-sts-0 cassandra]$ cat stderr.log 
Error opening zip file or JAR manifest missing : /opt/cdc_agent/cdc-agent.jar
[cassandra@test-cluster-dc1-default-sts-0 cassandra]$
```

This works in the DSE images, but not on the OSS UBI images. @Miles-Garnsey

**Comment by emerkle826** [comment]
I'll try to take a look at this today if I can

**Comment by emerkle826** [comment]
The issue was with the symlinking of the CDC agent jarfile. It was wrong in the UBI8 based images. In the Ubuntu based images, the file is moved, not linked, which is why it works there.
