### ISSUE TITLE
Make heap memory for the Management API configurable

### ISSUE THREAD

**Issue by jimdickinson** [k8ssandra/management-api-for-apache-cassandra#55]
I set the JVM heap with -Xms128m and -Xmx128m - we can probably set both lower. Also setting Netty to use less memory would be good.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-157) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-157
┆Priority: Medium

**Comment by emerkle826** [comment]
Might be better to make it so the min/max heap for Management API is configurable via an environment variable (with the default staying at the current 128m).
