### ISSUE TITLE
Migrate source repository to k8ssandra GH org

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/management-api-for-apache-cassandra#95]
As k8ssandra evolves a large swath of the growth in management-api will be driven via k8ssandra, so we'll be moving the management-api-for-apache-cassandra repo from datastax -> k8ssandra.

**Comment by emerkle826** [comment]
Done. Please update any local clones to point to the new location:

For HTTPS:
```
git remote set-url origin https://github.com/k8ssandra/management-api-for-apache-cassandra.git
```
or for SSH:
```
git remote set-url origin git@github.com:k8ssandra/management-api-for-apache-cassandra.git
```

**Comment by emerkle826** [comment]
The repo is transferred, but the documentation needs updating. Re-opening the issue until a PR is merged that updates the docs.
