### ISSUE TITLE
Migrate docker image repository to k8ssandra docker org

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/management-api-for-apache-cassandra#96]
As a companion to #95 we also want to consolidate the docker images generated for the management-api under the k8ssandra docker org.

Also included in this work should be a refactoring of the way the repositories are structured so that all management-api images are consolidated under a single repository with relevant tags applied denoting the various version options available.

We also should generate new naming conventions that avoid the Apache Cassandra trademarks.

This would consolidate all of the following repositories:

https://hub.docker.com/r/datastax/cassandra-mgmtapi-4_0_0
https://hub.docker.com/r/datastax/cassandra-mgmtapi-3_11_10
https://hub.docker.com/r/datastax/cassandra-mgmtapi-3_11_9
https://hub.docker.com/r/datastax/cassandra-mgmtapi-3_11_8
https://hub.docker.com/r/datastax/cassandra-mgmtapi-3_11_7

Note that we do *not* intend to move the DSE related management-api repository if possible:

https://hub.docker.com/r/datastax/dse-mgmtapi-6_8

**Comment by emerkle826** [comment]
As far as the tags go, are you wanting something like:

1) `cassandra-mgmtapi:4.0.0`
1) `cassandra-mgmtapi:3.11.10`
1) `cassandra-mgmtapi:3.11.9`
1) etc...

Or something like:

1) `cassandra-mgmtapi:4.0.0-v0.1.23`
1) `cassandra-mgmtapi:3.11.10-v0.1.23`
1) `cassandra-mgmtapi:3.11.9-v0.1.23`
1) etc...

I'm not a fan of the second version, but if they all end up in the same Docker repo, they need to be distinguished by Cassandra version and Management API version, so we may not have much of a choice.

**Comment by emerkle826** [comment]
A suggestion was brought up to create a tagging scheme such that a Cassandra-only tag would be equivalent to a `latest` tag. So something like:
`cassandra-mgmtapi:3.11.10`
would be the same as the latest
`cassandra-mgmtapi:3.11.10-X.Y.Z`

Also, the naming of the repo should probably be `cass-mgmtapi` as opposed to `cassandra-mgmtapi`

**Comment by emerkle826** [comment]
@bradfordcp @jdonenine @JeremiahDJordan Any comments on the tagging strategy, or the image rename on this?

**Comment by JeremiahDJordan** [comment]
what about `k8ssandra/management-api::3.11.10-vX.Y.Z` ?  But really I think any of those is fine.

**Comment by jdonenine** [comment]
>A suggestion was brought up to create a tagging scheme such that a Cassandra-only tag would be equivalent to a latest tag. So something like:
cassandra-mgmtapi:3.11.10
would be the same as the latest
cassandra-mgmtapi:3.11.10-vX.Y.Z

I'm cool with what's suggested here.
